### ISSUE TITLE
Keypad TODO

### ISSUE THREAD

**Issue by alancheung** [alancheung/Python.Repository#2]
Now
- [x] Face recognition........
- [x] Implement auto-clear
- [x] Add code for GPIO/relay control
- [x] Wire up 12V step-down converter
- [x] Create salt/hash combination file (needs discussion, use local file for now)
- [x] Reduce camera usage

Later
- [ ] Add ability to create new password
- [ ] Add logging to DHCPi
- [ ] Rotate display vertical (FUCK ME)
- [ ] LED?
